### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by Y-Haneji** [assembly-101/assembly101-download-scripts#12]
I'd like to download the data and at first tried `authenticate.py`.

It gave the url and I logged in my account to which you gave permission to access a Google Drive of the project. However, it gave an error that said "This app is blocked. This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

I found out that this might be related to this article (https://support.google.com/accounts/answer/6010255) but I couldn't turn on "Less secure app access".

**Comment by Y-Haneji** [comment]
I've also updated the `client_secrets.json` with the appropriate `client_secret`.

**Comment by Y-Haneji** [comment]
I tried `pydrive2` on my own Google Cloud Project, and it succeeded at authentication. It implies that the problem is not  originated from `pydrive2`.

**Comment by Y-Haneji** [comment]
This may be related. https://support.google.com/cloud/answer/7454865

**Comment by Y-Haneji** [comment]
I followed this (https://docs.iterative.ai/PyDrive2/quickstart/#authentication) instruction and made a credential in my own Google Cloud Project. Then I saved the credential as client_secrets.json. This worked for me.

**Comment by Oliverchhhh** [comment]
![Image](https://github.com/user-attachments/assets/b9e91074-4271-4441-8bb2-8e66cb1f8d41)
I creat my own project and save the credential as client_secrets.json in my work file,  but I went to my project instead of assembly101_download.

**Comment by hsattaru** [comment]
I cant authenticate myself even after following the link. is there any solution?
