### ISSUE TITLE
how to download metadata, camera intrinsics, poses@60fps, etc with PyDrive

### ISSUE THREAD

**Issue by relh** [assembly-101/assembly101-download-scripts#14]
Hi! I'm hoping to use the `download.py` script to download more than just the videos. 

I tried extracting the names of files in the GDrive and searching for them but it seems none of the files contain `.json`s from the poses@60fps folder. 

Any help would be appreciated and/or I'll post how I figure it out if I do.

**Comment by relh** [comment]
That was fast. I just found that I could iterate through the videos and add ".json" to them and then do this command:

my_list = drive.ListFile({'q': f"title='nusar-2021_action_both_9011-b06b_9011_user_id_2021-02-01_154253.json'"}).GetList()

And then the json showed up ^_^.

**Comment by gs-ren** [comment]
> That was fast. I just found that I could iterate through the videos and add ".json" to them and then do this command:
> 
> my_list = drive.ListFile({'q': f"title='nusar-2021_action_both_9011-b06b_9011_user_id_2021-02-01_154253.json'"}).GetList()
> 
> And then the json showed up ^_^.
> 
> EDIT: for anyone who wants easy mode this might work:
> 
> ```
>     jsons = list(set([x.split('/')[0] for x in master_dict.keys()]))
>     json_objs = []
>     for x in jsons:
>         json_objs = drive.ListFile({'q': f"title='{x}.json'"}).GetList()
>         if len(json_objs) > 0:
>             json_objs[0].GetContentFile(json_objs[0]['title'])
> ```

Hi， how about the file metadata.zip?  Could you please share how to download it by download.py ?  @relh
