### ISSUE TITLE
Failure to generate the credentials.json with authenticate.py

### ISSUE THREAD

**Issue by fylwen** [assembly-101/assembly101-download-scripts#2]
Hi. 

When I execute the _authenticate.py_, I cannot generate the _credentials.json_: The localhost:8080 in my local chrome browser shows the message "The authentication flow has completed", but the console of my terminal reports bugs, as shown in the attached image. 
![pic](https://user-images.githubusercontent.com/48756873/194229071-0dd128a7-7d28-48f5-8720-ab3ec5c9b4cd.png)

And therefore I write to seek your help.
Thanks a lot.

Best regards,
Frances

**Comment by assembly-101** [comment]
Hi,

The `clients_secret.json` file that you downloaded with this repo does not come with the `client_secret` key.

As mentioned [here](https://github.com/assembly-101/assembly101-download-scripts#this-repository-contains-the-following-files), please input the `client_secret` key (which was sent to you along with the dataset access) in the required field in the `clients_secret.json` file.

This should solve your issue.

**Comment by fylwen** [comment]
Thanks for your help!
