### ISSUE TITLE
File list empty

### ISSUE THREAD

**Issue by finlay96** [assembly-101/assembly101-download-scripts#24]
Hi there,

Trying to download the dataset, authentication has been completed with the OAuth method given in: https://docs.iterative.ai/PyDrive2/quickstart/#authentication

However, the download.py is gettting empty file lists within:
```
def getAllFiles(video_name, video_id):
	file_list = drive.ListFile({'q' : f"'{video_id}' in parents and trashed=false"}).GetList()
```
Is there any idea of why this could be or any options for solving this.

Thanks!
Finlay

**Comment by assembly-101** [comment]
Hi, did you put the `client_secret` key (that was sent to you when you were granted access to the drive) in the `client_secrets.json` file ?

Also, can you send me the script you are using to download the videos ?

**Comment by finlay96** [comment]
So it was a missing key in the .json file in the end. Thank you for solving!
