### ISSUE TITLE
How to get the metadeta.zip

### ISSUE THREAD

**Issue by HouTong-s** [assembly-101/assembly101-download-scripts#25]
Hi! Author.
I find there  no "metadeta.zip" in the google drive.Could you please add that meta file in it?
![image](https://github.com/user-attachments/assets/e96c232b-75e6-4697-b868-822dab1d6e3b)

**Comment by assembly-101** [comment]
Hi,

Thank you for bringing this to our attention. We recently repacked all metadata + some additional files inside `AssemblyPoses.zip`.

We have updated our README with this information.

Thanks,
Assembly101 Team
