### ISSUE TITLE
missing hand poses

### ISSUE THREAD

**Issue by tqosu** [assembly-101/assembly101-download-scripts#26]
"Poses are provided for 337 out of 362 sequences in the Assembly101 dataset."

https://github.com/s-shamil/HandFormer/issues/4

Is there a reason for this?

Thanks.

**Comment by assembly-101** [comment]
Hi,

Hand poses are extracted from egocentric views. However, we encountered issues with several recordings that had corrupt or failed egocentric streams. As a result, we do not have hand poses extracted for a few recordings.

Best,
Assembly101 Team

**Comment by tqosu** [comment]
Thanks.
