### ISSUE TITLE
Camera Intrinsics for the 12 views

### ISSUE THREAD

**Issue by fylwen** [assembly-101/assembly101-download-scripts#3]
Hi. I wonder whether the camera intrinsics for the 12 views can be provided, so that I can project the provided 3D hand pose into images of respective views.

Thanks for your help!

Best regards,
Frances

**Comment by assembly-101** [comment]
Hi,

We are currently preparing this data for release.
However, we noticed some issues in certain recordings and we are checking these to be sure that the data is accurate.

Please find some of the verified recordings in this [link](https://drive.google.com/drive/folders/1nNj5Z8v73brMJKBZxLjvVxJOaIMpDHUx?usp=sharing).

Hope this helps for now.

Best,
The Assembly101 Team
