### ISSUE TITLE
Correspondence between actual hand joints to row index of per-frame hand pose

### ISSUE THREAD

**Issue by fylwen** [assembly-101/assembly101-download-scripts#5]
Hi. For the per-frame pose labels provided in the poses@60fps folder, I wonder what is the correspondence between actual hand joints and the row index for "0" and "1" in per-frame landmarks, as well as which of the "0" and "1" represents the right hand?

Thanks.

**Comment by fylwen** [comment]
Hi, thanks for the information.

Another question is that there seem to be 21 joints for each hand, but only the first 20 joints (i.e., index with 0~19) are involved in the inward; what about the joint with index 20?

Thanks!

**Comment by assembly-101** [comment]
Hi Frances.

We did not use the last joint (index 20: "Palm center") but it could be connected to joint index 5: "Wrist joint".

<img width="1140" alt="Screenshot 2022-11-01 at 4 31 08 PM" src="https://user-images.githubusercontent.com/100765171/199191788-3a0e1ba8-155e-4afa-a580-dc9aa260dc8f.png">
