### ISSUE TITLE
Google Drive Issue

### ISSUE THREAD

**Issue by hitcbw** [assembly-101/assembly101-download-scripts#6]
Hi, I get an access code and write it into the client_secrets.json. Run authenticate.py will lead me to browser and I authenticate the app "download". After that, it tells me "The authentication flow has completed". Nothing happened then and I can't do anything. How can I solve this problem?

**Comment by hitcbw** [comment]
Hi,
1. I want to download the dataset via python script, with the local machine (windows11, with browser)
2. I have access to the dataset with a client_secret
3. I write the client_secret into client_secrets.json
4. run download.py, then my browser will be opened to visit google oauth2
5. I grant access to "download" to access my google account
6.  A page shows "The authentication flow has completed." raised on localhost:8080
7. Then nothing happened until the socket connection is timeout.

**Comment by assembly-101** [comment]
Hi,

After you have been granted access to download i.e. pt.6, the downloading of videos should begin automatically.

Are you authenticating with the same google account that you have been given access to? And subsequently, can you check if `credentials.json` file has been created in your working directory after the authentication is completed?

Is any error message shown in your terminal ?
After authentication is completed your terminal should output `Authentication successful.` and then there should be a progress (tqdm) bar denoting the progress of your download.

**Comment by hitcbw** [comment]
Hi,
thanks for your reply. There is no credentials.json been created and "no credentials.json" error shown in my terminal before authentication. The account is as same as been given access to. After pt.6, nothing happened. It's weird -_-. 
If nobody else has this problem, I think I should try another account and close this issue.

**Comment by assembly-101** [comment]
Can you try a fresh clone of the repo and run `authenticate.py` to generate the `credentials.json` - if it generated then your problem should be solved.

**Comment by yayuanli** [comment]
Hi,
I have exactly the same issue when I try to generate credentials.json on my local machine. I got exactly what hitcbw got but also, I noticed in the terminal I go following error:

```
$ python authenticate.py
/path/to/assembly101/python/env/lib/python3.10/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access credentials.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=911520126045-8bn01n7p49kq5nnt8jffg2ldc5pt6m2i.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code&approval_prompt=force

Traceback (most recent call last):
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/pydrive2/auth.py", line 698, in Authenticate
    self.credentials = self.flow.step2_exchange(code)
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/oauth2client/client.py", line 2089, in step2_exchange
    raise FlowExchangeError(error_msg)
oauth2client.client.FlowExchangeError: invalid_requestclient_secret is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/assembly101-download-scripts/authenticate.py", line 20, in <module>
    file_list = drive.ListFile({'q' : f"'{folder}' in parents and trashed=false"}).GetList()
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/pydrive2/apiattr.py", line 163, in GetList
    for x in self:
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/pydrive2/apiattr.py", line 147, in __next__
    result = self._GetList()
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/pydrive2/auth.py", line 60, in _decorated
    self.auth.LocalWebserverAuth()
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/pydrive2/auth.py", line 136, in _decorated
    self.Auth(code)
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/pydrive2/auth.py", line 685, in Auth
    self.Authenticate(code)
  File "/path/to/assembly101/python/env/lib/python3.10/site-packages/pydrive2/auth.py", line 700, in Authenticate
    raise AuthenticationError("OAuth2 code exchange failed: %s" % e)
pydrive2.auth.AuthenticationError: OAuth2 code exchange failed: invalid_requestclient_secret is missing.
```

Any clue why this happend? 

Thank you,

**Comment by yayuanli** [comment]
Solved. Before we run `authenticate.py`, we should add the client key (the one in the google drive access granted email) into `client_secrets.json`. @hitcbw 

@assembly-101 Could you please indicate this point into the [instruction](https://github.com/assembly-101/assembly101-download-scripts#authentication)? Thank you.

**Comment by assembly-101** [comment]
Hi,

We already have this information mentioned [here](https://github.com/assembly-101/assembly101-download-scripts#this-repository-contains-the-following-files).

**Comment by yayuanli** [comment]
I was following that one. People usually check the line of `authenticate.py` first which leads to [Authenticate instruction](https://github.com/assembly-101/assembly101-download-scripts#authentication). That's when people don't have the client key added yet. That's why me (maybe and @hitcbw) came across this error. 

Sure people will finally find out the solution when the continue reading [the file explanation](https://github.com/assembly-101/assembly101-download-scripts#this-repository-contains-the-following-files) but explicity adding the "adding client key" prerequisite into the Authenticate instruction can prevent this struggle. 

Just a suggestion. Cheers.

**Comment by assembly-101** [comment]
Hi Yayuan,

Thanks for this suggestion. Will update the section accordingly.

Best,
Assembly101 Team
