### ISSUE TITLE
Error when downloading video file (QuotaExceeded)

### ISSUE THREAD

**Issue by fylwen** [assembly-101/assembly101-download-scripts#7]
Hello, when i try to download the file in a new environment, I find that I failed to down any of them. While i was tracking the execusion of the download.py, I found the following exception:

> Traceback (most recent call last):
>   File "/ghome/l5/ylwen/anaconda3/envs/hand39/lib/python3.9/site-packages/pydrive2/files.py", line 338, in GetContentFile
>     download(
>   File "/ghome/l5/ylwen/anaconda3/envs/hand39/lib/python3.9/site-packages/pydrive2/files.py", line 328, in download
>     status, done = downloader.next_chunk()
>   File "/ghome/l5/ylwen/anaconda3/envs/hand39/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "/ghome/l5/ylwen/anaconda3/envs/hand39/lib/python3.9/site-packages/googleapiclient/http.py", line 780, in next_chunk
>     raise HttpError(resp, content, uri=self._uri)
> googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/1L4_EzFtZr1zaEjUE_gwn3_NqjXkxf2jU?acknowledgeAbuse=false&alt=media returned "The download quota for this file has been exceeded". Details: "[{'domain': 'usageLimits', 'reason': 'quotaExceeded', 'message': 'The download quota for this file has been exceeded', 'locationType': 'other', 'location': 'quota.download'}]">
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/ghome/l5/ylwen/HOA/ass101/download-scripts/download.py", line 139, in <module>
>     download_file(out_path, video_name, video_file)
>   File "/ghome/l5/ylwen/HOA/ass101/download-scripts/download.py", line 79, in download_file
>     file.GetContentFile(file['title'])
>   File "/ghome/l5/ylwen/anaconda3/envs/hand39/lib/python3.9/site-packages/pydrive2/auth.py", line 84, in _decorated
>     return decoratee(self, *args, **kwargs)
>   File "/ghome/l5/ylwen/anaconda3/envs/hand39/lib/python3.9/site-packages/pydrive2/files.py", line 350, in GetContentFile
>     raise exc
> pydrive2.files.ApiRequestError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/1L4_EzFtZr1zaEjUE_gwn3_NqjXkxf2jU?acknowledgeAbuse=false&alt=media returned "The download quota for this file has been exceeded". Details: "[{'domain': 'usageLimits', 'reason': 'quotaExceeded', 'message': 'The download quota for this file has been exceeded', 'locationType': 'other', 'location': 'quota.download'}]">
> 

Therefore I write to seek your help. Thank you so much for your valuable time and help.

Best regards,
Frances

**Comment by assembly-101** [comment]
Hi Frances,

Sometimes, when the traffic is huge, Google Drive API temporarily blocks the download and that will throw the above mentioned error. The best solution is to retry the next day as the drive server is updated every 24 hours.

Add `--resume` while running `download.py` to download only those videos that failed in the first place.

Let us know if this solves your problem.

Best regards,
The Assembly101 team
