### ISSUE TITLE
Issues when downloading file to different file system (and other potential issues)

### ISSUE THREAD

**Issue by Shivvrat** [assembly-101/assembly101-download-scripts#8]
Hey. I would first like to thank you all for the dataset!

I had a suggestion for the video download process. In the following lines - 

```
        try:
		file.GetContentFile(file['title'])
		os.rename(f'{file_name}', f'{out_path}/{file_name}')
	except:
		# if any video fails to download completely, its name will be stored in error_downloading.txt
		with open('./error_downloading.txt', 'a') as f:
			f.write(f'{out_path}/{file_name}\n')
		os.remove(f'{file_name}')
```

when you add the name to error_downloading.txt, can you also save the exception that we get? It would greatly help to debug why the dataset is not being downloaded. 

I tried to download it, and after removing the `except`, I was able to figure out that I was getting `OSError: [Errno 18] Invalid cross-device link` because I was trying to store the data on another drive!

Thanks again!

**Comment by assembly-101** [comment]
Hi Shivvrat,

Thanks for the suggestion. We will integrate it in your code.

Best,
The Assembly101 team

**Comment by avijit9** [comment]
I modified the code block as follows - 
```

try:
		file.GetContentFile(file['title'])
		# os.rename(f'{file_name}', f'{out_path}/{file_name}')
		import shutil
		shutil.move(f'{file_name}', f'{out_path}/{file_name}')
	except Exception as e:
		# if any video fails to download completely, its name will be stored in error_downloading.txt
		print(f'=> [Error encountered]: {e}')
		with open('./error_downloading.txt', 'a') as f:
			f.write(f'{out_path}/{file_name}\n')
		os.remove(f'{file_name}')
```
