### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by Camillo4eyes** [assembly-101/assembly101-download-scripts#9]
Hi, trying to download (only the egocentric view) the code stops without downloading the videos and without reporting any error. How to fix?
![issue](https://user-images.githubusercontent.com/26376030/220721634-f93f84ee-1b7c-46d0-a90c-71def2afc78a.png)

**Comment by assembly-101** [comment]
Hi,

Are you still facing this issue ?
According to the suggestion made in [Issue#8](https://github.com/assembly-101/assembly101-download-scripts/issues/8), we have added an extra statement to print the error when a video does not download.

Hope that helps.

Best,
Assembly101 team
